"""
Prometheus metrics for the Autonomous Research System.

Exposes counters, histograms, and gauges for monitoring:
- Planner: latency, request count
- Retrieval: latency, failures
- Synthesizer: latency, token count
- Critic: latency, average score
- System-wide: avg response time, total queries
"""
from prometheus_client import Counter, Histogram, Gauge
import time
from functools import wraps

# =============================================================================
# PLANNER METRICS
# =============================================================================
planner_latency = Histogram(
    "planner_latency_seconds",
    "Latency of planner agent (sub-question generation)",
    buckets=[0.1, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0],
)
requests_total = Counter(
    "requests_total",
    "Total number of planner requests",
    ["agent"],
)

# =============================================================================
# RETRIEVAL METRICS
# =============================================================================
retrieval_latency = Histogram(
    "retrieval_latency_seconds",
    "Latency of retrieval agent (document search)",
    buckets=[0.1, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0],
)
failures_total = Counter(
    "failures_total",
    "Total number of retrieval failures",
    ["agent"],
)

# =============================================================================
# SYNTHESIZER METRICS
# =============================================================================
synthesizer_latency = Histogram(
    "synthes_latency_seconds",
    "Latency of synthesizer agent (answer generation)",
    buckets=[0.5, 1.0, 2.5, 5.0, 10.0, 30.0, 60.0],
)
synthesis_tokens_total = Counter(
    "synthesis_tokens_total",
    "Total number of tokens generated by synthesizer",
    ["agent"],
)

# =============================================================================
# CRITIC METRICS
# =============================================================================
critic_latency = Histogram(
    "critic_latency_seconds",
    "Latency of critic agent (answer evaluation)",
    buckets=[0.1, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0],
)
critic_avg_score = Gauge(
    "critic_avg_score",
    "Average quality score from critic agent (0-100)",
    ["agent"],
)

# =============================================================================
# SYSTEM-WIDE METRICS
# =============================================================================
avg_response_time = Histogram(
    "avg_response_time_seconds",
    "End-to-end response time for query API",
    buckets=[0.5, 1.0, 2.5, 5.0, 10.0, 30.0, 60.0, 120.0],
)
total_queries = Counter(
    "total_queries",
    "Total number of queries processed by the system",
    ["endpoint"],
)

# Cache hit/miss tracking
cache_hits = Counter("cache_hits", "Total cache hits", ["endpoint"])
cache_misses = Counter("cache_misses", "Total cache misses", ["endpoint"])


def observe_latency(histogram: Histogram):
    """Decorator to observe latency of a function via a histogram."""
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            start = time.time()
            try:
                result = func(*args, **kwargs)
                return result
            finally:
                elapsed = time.time() - start
                histogram.observe(elapsed)
        return wrapper
    return decorator


async def observe_latency_async(histogram: Histogram, func, *args, **kwargs):
    """Observe latency of an async function."""
    start = time.time()
    try:
        result = await func(*args, **kwargs)
        return result
    finally:
        elapsed = time.time() - start
        histogram.observe(elapsed)